name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Runs when you push to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-marks-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/student-marks-api:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2 (or ECS)
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/student-marks-api:latest
            docker stop student-marks-api || true
            docker rm student-marks-api || true
            docker run -d -p 8000:8000 --name student-marks-api ${{ secrets.DOCKER_USERNAME }}/student-marks-api:latest
          EOF
